// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoYxBlrE4BhPt1D0JBV8XkwK9VsC3OBoI',
    appId: '1:494150941094:web:e11ae976d4216c0a50f767',
    messagingSenderId: '494150941094',
    projectId: 'post-ecbf0',
    authDomain: 'post-ecbf0.firebaseapp.com',
    storageBucket: 'post-ecbf0.firebasestorage.app',
    measurementId: 'G-5VFPQ7C3K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnHB2oZV-z1oI7KLIzw3QOrT9-k20sSd4',
    appId: '1:494150941094:android:c779480f1835455150f767',
    messagingSenderId: '494150941094',
    projectId: 'post-ecbf0',
    storageBucket: 'post-ecbf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeFTjjqo5FzcRm-Xk6SazjsqX9IZVPHkI',
    appId: '1:494150941094:ios:25fd635a59d0dcca50f767',
    messagingSenderId: '494150941094',
    projectId: 'post-ecbf0',
    storageBucket: 'post-ecbf0.firebasestorage.app',
    iosBundleId: 'com.example.firebase2',
  );
}
